model:
  model_type: implisat
  n_input_dims: 2
  n_output_dims: 1
  n_neurons: 256
  n_fourier_bases: 4096
  n_layers: 4
  outermost_linear: true
  first_omega_0: 30
  hidden_omega_0: 30
  output_activation: Sigmoid
  is_phase1d: false

train:
  uid: ~ # this evaluates to literal None in python whereas writing None would evaluate to string of 'None'
  epoch: 10000
  lr: !!float 5e-4
  num_workers: 4
  log_dir: logs/implisat
  early_stop_patience: 1000
  lr_decay_patience: 250
  lr_decay_factor: 0.5
  img_log_interval: 999
  visualize_per_channel: true
  use_checkpointing: true

data:
  path: dataset/seoul_aligned.tif
  normalize_per_channel: true
  n_splits: 1
  is_sentinel: true
